Context に応じた Injector を利用可能に
ray-di/Ray.RayDiForLaravel pull request #4
Opened 2022-05-21 16:54 UTC by NaokiTsuchiya

# 概要

`CachedInjectorFactory` を使い、context に応じて利用する injector を変更できるようにします。

# 方法

## bootstrap

次のような bootstrap になります。

```diff
- $app = new Illuminate\Foundation\Application(
-     $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
- );
+ $app = (new Ray\RayDiForLaravel\ApplicationFactory())(
+     $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__),
+     new PrdContext()
+ );
```

`PrdContext` は `Ray\RayDiForLaravel\AbstractContext` を継承した次のようなクラスで、
`CachedInjectorFactory` で利用するパラメータを定義します。

```php
<?php

declare(strict_types=1);

namespace App\Contexts;

use Ray\Di\AbstractModule;
use Ray\RayDiForLaravel\AbstractContext;

class PrdContext extends AbstractContext
{
    public function getModule(): AbstractModule
    {
        return new MyModule();
    }

    public function isCacheable(): bool
    {
        return true;
    }

    public function getSavedSingleton(): array
    {
        return [];
    }
}
```

2022-05-21 16:56 UTC, NaokiTsuchiya commented
@koriym レビューお願いします

2022-05-22 04:46 UTC, koriym commented
@NaokiTsuchiya 汎用化できる部分をRay.Compilerの方にPR作成しました。

https://github.com/ray-di/Ray.Compiler/pull/86

2022-05-22 04:47 UTC, koriym commented
Cacheの部分はキャッシュオブジェクトを返すように変更しています。

2022-05-22 09:46 UTC, koriym commented
LGTM
Ray.Compiler進めましょうか！

2022-05-27 12:34 UTC, koriym commented
@NaokiTsuchiya Symfony Cache外しましょうか？

2022-05-28 00:14 UTC, koriym requested changes
READMEの変更も必要ですね。

2022-05-31 04:55 UTC, koriym commented
新しいRay.Compilerを適用しました。今までのオンデマンドでコンパイルされていたものの明示的な束縛(Untarget)が必要になりました。

2022-06-03 07:42 UTC, koriym commented on composer.json
> +        "doctrine/cache": "^1.10"
```suggestion
        "doctrine/cache": "^1.10 || ^2.2"
```

doctrine/cache2を使ってクラアインとが他のキャッシュを選択するときに必要？

2022-06-10 08:10 UTC, koriym approved these changes

2022-06-10 08:10 UTC, merged